import type { Metadata } from "next";
import Link from "next/link";
import { ExternalLinkIcon } from "@/components/icons";
import "./globals.css";

export const metadata: Metadata = {
  title: "Army Doctrine Assistant",
  description:
    "Search and ask questions across all 51 active U.S. Army Field Manuals. Answers cited to the exact FM section.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-screen flex flex-col bg-gradient-to-b from-stone-50 to-white text-gray-900 font-sans antialiased">
        <SiteHeader />
        <div className="flex-1">{children}</div>
        <SiteFooter />
      </body>
    </html>
  );
}

function SiteHeader() {
  return (
    <header className="sticky top-0 z-40 border-b border-brand-800 bg-brand-900/95 backdrop-blur supports-[backdrop-filter]:bg-brand-900/80">
      <div className="mx-auto flex max-w-5xl items-center gap-3 px-4 py-3">
        <Link href="/" className="group flex items-center gap-2.5">
          <Emblem />
          <span className="leading-tight">
            <span className="block font-semibold tracking-tight text-white">
              Army Doctrine Assistant
            </span>
            <span className="block text-[11px] text-brand-300">
              51 active Field Manuals · AI research
            </span>
          </span>
        </Link>
        <nav className="ml-auto flex items-center gap-4 text-sm">
          <Link
            href="/"
            className="text-brand-100 transition-colors hover:text-white"
          >
            Library
          </Link>
          <a
            href="https://armypubs.army.mil"
            target="_blank"
            rel="noopener noreferrer"
            className="hidden items-center gap-1 text-brand-300 transition-colors hover:text-white sm:flex"
          >
            armypubs.army.mil
            <ExternalLinkIcon className="h-3 w-3" />
          </a>
        </nav>
      </div>
    </header>
  );
}

function SiteFooter() {
  return (
    <footer className="mt-16 border-t border-gray-200 bg-white/60">
      <div className="mx-auto max-w-5xl px-4 py-8 text-xs leading-relaxed text-gray-500">
        Field manuals are public-domain U.S. government publications, sourced
        from{" "}
        <a
          href="https://armypubs.army.mil"
          target="_blank"
          rel="noopener noreferrer"
          className="text-brand-700 underline-offset-2 hover:underline"
        >
          armypubs.army.mil
        </a>
        . Answers are generated by Claude and may contain errors — always verify
        against the cited source. Not affiliated with the U.S. Army or DoD.
      </div>
    </footer>
  );
}

/** Small shield-and-star mark used in the header. */
function Emblem() {
  return (
    <span className="flex h-8 w-8 items-center justify-center rounded-md bg-brand-700 ring-1 ring-brand-600/60 transition-colors group-hover:bg-brand-600">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden>
        <path
          d="M12 2 4 5v6c0 4.4 3.2 8.3 8 9.5 4.8-1.2 8-5.1 8-9.5V5l-8-3Z"
          fill="#d6b84e"
          stroke="#d6b84e"
          strokeWidth="0.5"
          strokeLinejoin="round"
        />
        <path
          d="m12 7 1.3 2.8 3 .3-2.2 2 .6 3-2.7-1.5-2.7 1.5.6-3-2.2-2 3-.3L12 7Z"
          fill="#2b3527"
        />
      </svg>
    </span>
  );
}
